{% set name = "des-y6utils" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/des-science/des-y6utils/archive/refs/tags/{{ version }}.tar.gz
  sha256: d094ec8cbb97424d58459feb1da16cba681ff4c02683ce804e4baad11e5288f4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.7
    - ngmix
    - galsim
    - numpy
    - piff
    - scipy
    - scikit-learn
    - healsparse

test:
  imports:
    - des_y6utils
    - des_y6utils.piff
    - des_y6utils.mdet

about:
  home: https://github.com/des-science/des-y6utils
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: random bits of useful code for Y6 analysis

extra:
  recipe-maintainers:
    - beckermr
