{% set name = "des-y6utils" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/des-science/des-y6utils/archive/refs/tags/{{ version }}.tar.gz
  sha256: ee3c3271ac6092696efa04b328eb3b6145ad1a0377fcd5db00dca5f76d54fd0e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm <6.1
    - setuptools_scm_git_archive
  run:
    - python >=3.6
    - ngmix
    - galsim
    - numpy
    - piff
    - scipy
    - scikit-learn

test:
  imports:
    - des_y6utils
    - des_y6utils.piff

about:
  home: https://github.com/des-science/des-y6utils
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: random bits of useful code for Y6 analysis

extra:
  recipe-maintainers:
    - beckermr
